FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY TechMoveLogisticsApplication/TechMoveLogisticsApplication.csproj TechMoveLogisticsApplication/
COPY TechMoveLogisticsAPI/TechMoveLogisticsAPI/TechMoveLogisticsAPI.csproj TechMoveLogisticsAPI/TechMoveLogisticsAPI/
RUN dotnet restore TechMoveLogisticsAPI/TechMoveLogisticsAPI/TechMoveLogisticsAPI.csproj
COPY TechMoveLogisticsApplication/ TechMoveLogisticsApplication/
COPY TechMoveLogisticsAPI/TechMoveLogisticsAPI/ TechMoveLogisticsAPI/TechMoveLogisticsAPI/
RUN rm -f TechMoveLogisticsApplication/appsettings*.json
WORKDIR /src/TechMoveLogisticsAPI/TechMoveLogisticsAPI
RUN dotnet publish TechMoveLogisticsAPI.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM runtime AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "TechMoveLogisticsAPI.dll"]
